MNT: Update uv.lock
Update uv.lock file. Fixes:
```
error: Failed to parse `uv.lock`
  Caused by: For package `imageio==2.37.4 @
  registry+https://pypi.org/simple`, found dependency `numpy==2.2.6`
  with no locked package
```